on: [push]
name: Web App
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create Resource Group
      run: |
        az group create --name myResourceGroup --location westeurope
    - name: Create SQL Database
      run: |
        az sql server create --name mySqlServerHW --resource-group myResourceGroup --location westeurope --admin-user mateidoncu --admin-password 0P4r0l4S3cr3t4
        az sql db create --name mySqlDatabaseHW --resource-group myResourceGroup --server mySqlServerHW --service-objective S0
    - name: Create Web App
      run: |
        az appservice plan create --name myAppServicePlan --resource-group myResourceGroup --sku F1 --location westeurope
        az webapp create --name myWebAppHW --plan myAppServicePlan --resource-group myResourceGroup
    - name: Create Autoscale Setting
      run: |
        az monitor autoscale create --name myAutoscaleSetting --resource-group myResourceGroup --resource /subscriptions/d88d55f2-1edf-4ccb-9721-9946addbeec7/resourceGroups/myResourceGroup/providers/Microsoft.Web/sites/myWebAppHW --location westeurope --min-count 1 --max-count 10 --count 1 --email-administrator admin@example.com --operator GreaterThan --metric "Percentage CPU" --threshold 80

    - name: Create Alert Rule
      run: |
        az monitor metrics alert create --name myAlertRule --resource-group myResourceGroup --resource /subscriptions/<subscription-id>/resourceGroups/myResourceGroup/providers/Microsoft.Web/sites/myWebAppHW --condition "Percentage CPU > 80" --description "CPU usage is high" --action doncumatei@yahoo.com
    - name: Create App Insights
      run: |
        az monitor app-insights component create --app myAppInsights --resource-group myResourceGroup --location westeurope
        az webapp config appsettings set --name myWebAppHW --resource-group myResourceGroup --settings "APPINSIGHTS_INSTRUMENTATIONKEY=<instrumentation-key>"
