on: [push]
name: Web App
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create Resource Group
      run: |
        az group create --name myResourceGroup --location westeurope
    - name: Create SQL Database
      run: |
        az sql server create --name mySqlServerHW --resource-group myResourceGroup --location westeurope --admin-user mateidoncu --admin-password 0P4r0l4S3cr3t4
        az sql db create --name mySqlDatabaseHW --resource-group myResourceGroup --server mySqlServerHW --service-objective S0
    - name: Create Web App
      run: |
        az appservice plan create --name myAppServicePlan --resource-group myResourceGroup --sku F1 --location westeurope
        az webapp create --name myWebAppHW --plan myAppServicePlan --resource-group myResourceGroup
    - name: Create Autoscale Setting
      run: |
         az monitor autoscale create --resource-group myResourceGroup --resource myAppServicePlan --min-count 1 --max-count 4 --count 1 --email-administrator --resource-type Microsoft.Web/serverfarms
    - name: Create Autoscale Rule
      run: |
        az monitor autoscale rule create --resource-group myResourceGroup --autoscale-name myAppServicePlan --scale in 1 --condition "CpuPercentage <= 40 avg 10m"
    - name: Create Alert Rule
      run: |
        az monitor metrics alert create --name myAlert --resource-group myResourceGroup --scopes /subscriptions/d88d55f2-1edf-4ccb-9721-9946addbeec7/resourceGroups/myResourceGroup/providers/Microsoft.Web/serverfarms/myAppServicePlan --condition "avg CpuPercentage > 80" --description "Alert when CPU usage is over 80%"
    - name: Create App Insights
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        az monitor app-insights component create --app myAppInsights --resource-group myResourceGroup --location westeurope
        az webapp config appsettings set --name myWebAppHW --resource-group myResourceGroup --settings "APPINSIGHTS_INSTRUMENTATIONKEY=<instrumentation-key>"
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/login@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_CREDENTIALS }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "/wwwroot" # App source code path
        api_location: "" # Api source code path - optional
        output_location: "/" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/login@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_CREDENTIALS }}
          action: "close"
